log_dir: "outputs/training/f0"
save_freq: 10
device: "cuda"
epochs: 100
batch_size: 8
pretrained_model: ""
train_data: "datasets/train_list.txt"
val_data: "datasets/val_list.txt"
num_workers: 4

preprocess_params:
  sr: 44100
  segment_size: 49152
  spect_params:
    n_mels: 80
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    f_min: 50
    f_max: 16000
  mel_params:
    n_mels: 80
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    f_min: 50
    f_max: 16000
  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.1
  
